export {
  parseInstant,
  getParisDateKey,
  endOfParisDay,
  getActivityStart,
  getActivityEnd,
  getRegistrationDeadline,
  isRegistrationOpen,
  isInProgress,
  shouldAutoEndSuccess,
  getRecruitingPhase,
  isProposalExpired,
  getActivityBadge,
  getRegistrationButtonLabel,
  canRegister,
  isRecruitingOnHome,
  isMultiDay,
  isStartingSoon,
  isLastChance,
  getActivityTags,
  BADGE_LABELS,
  TAG_LABELS,
  type RecruitingPhase,
  type ActivityBadgeKind,
  type ActivityTag,
} from '../../shared/activityPhase'
