import type { EnvConfig } from '@/shared/types'

export function getEnvConfig(env?: EnvConfig): EnvConfig {
  if (env) return env
  return {
    STORAGE_BACKEND: process.env.STORAGE_BACKEND,
    GOOGLE_SHEETS_ID: process.env.GOOGLE_SHEETS_ID,
    GOOGLE_SERVICE_ACCOUNT_JSON: process.env.GOOGLE_SERVICE_ACCOUNT_JSON,
    SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? process.env.SUPABASE_URL,
    SUPABASE_SERVICE_KEY:
      process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_SERVICE_KEY,
    TENCENT_DOCS_APP_ID: process.env.TENCENT_DOCS_APP_ID,
    TENCENT_DOCS_APP_SECRET: process.env.TENCENT_DOCS_APP_SECRET,
    CLAUDE_API_KEY: process.env.CLAUDE_API_KEY,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    GEMINI_API_KEY: process.env.GEMINI_API_KEY,
    GEMINI_MODEL: process.env.GEMINI_MODEL,
    ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
    SITE_URL: process.env.NEXT_PUBLIC_SITE_URL ?? process.env.SITE_URL,
    PARSE_MODE: process.env.PARSE_MODE,
    CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL,
    RESEND_FROM_NAME: process.env.RESEND_FROM_NAME,
    RESEND_TEST_EMAIL: process.env.RESEND_TEST_EMAIL,
  }
}
